accounts/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import login, logout, cadastro, UserUpdateView


urlpatterns = [
    path('', login, name='index_login'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('cadastro/', cadastro, name='cadastro'),
    path('update/<int:pk>', UserUpdateView.as_view(), name='update'),
]

gestorAtividades/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('diarioAtividades.urls')),
    path('', include('controleFrequencia.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    nome = models.CharField(default='***', max_length=100)
    sobrenome = models.CharField(default='***', max_length=100)
    matricula = models.CharField(default='***', max_length=9)
    chefia = models.CharField(default='***', max_length=100)
    setor = models.CharField(default='***', max_length=100)
    email = models.EmailField(default='a@b.com', null=False, blank=False)
    usuario = models.CharField(default='***', max_length=100)
    entrada = models.CharField(default='***', max_length=100)
    saidaAlmoco = models.CharField(default='***', max_length=100)
    voltaAlmoco = models.CharField(default='***', max_length=100)
    saida = models.CharField(default='***', max_length=100)

accounts/forms.py
from django.forms import ModelForm
from .models import User
from django.contrib import messages


class FormUpdateUser(ModelForm):
    class Meta:
        model = User
        fields = ('matricula', 'chefia', 'setor', 'entrada',
                  'saidaAlmoco', 'voltaAlmoco', 'saida')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from .models import User
from .forms import FormUpdateUser
from django.views.generic.edit import UpdateView


# Create your views here.
def login(request):
    if request.method != 'POST':
        return render(request, 'login.html')

    usuario = request.POST.get('usuario')
    senha = request.POST.get('senha')

    user = auth.authenticate(username=usuario, password=senha)

    if not user:
        messages.error(request, 'Usuário ou senha inválidos!')
        return render(request, 'login.html')
    else:
        auth.login(request, user)
        messages.success(request, 'Seja bem vindo!')
        return redirect('index')

    return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('login')

def cadastro(request):
    if request.method != 'POST':
        return render(request, 'cadastro.html')

    nome = request.POST.get('nome')
    sobrenome = request.POST.get('sobrenome')
    matricula = request.POST.get('matricula')
    chefia = request.POST.get('chefia')
    setor = request.POST.get('setor')
    email = request.POST.get('email')
    usuario = request.POST.get('usuario')
    entrada = request.POST.get('entrada')
    saidaAlmoco = request.POST.get('saidaAlmoco')
    voltaAlmoco = request.POST.get('voltaAlmoco')
    saida = request.POST.get('saida')
    senha = request.POST.get('senha')
    senha2 = request.POST.get('senha2')

    if not nome or not sobrenome or not matricula or not chefia or not setor or \
            not email or not usuario or not entrada or not saidaAlmoco or not voltaAlmoco or \
            not saida or not senha or not senha2:
        messages.error(request, 'Nenhum campo pode estar vazio!')
        return render(request, 'cadastro.html')

    if senha != senha2:
        messages.error(request, 'Os campos de senha e confirmação precisam ser iguais!')
        return render(request, 'cadastro.html')

    if User.objects.filter(username=usuario).exists():
        messages.error(request, 'Usuário já existe!')
        return render(request, 'cadastro.html')

    user = User.objects.create_user(username=usuario, email=email, password=senha,
                                    first_name=nome, last_name=sobrenome,
                                    matricula=matricula, chefia=chefia,
                                    setor=setor, entrada=entrada,
                                    saidaAlmoco=saidaAlmoco, voltaAlmoco=voltaAlmoco,
                                    saida=saida, nome=nome, sobrenome=sobrenome,
                                    usuario=usuario)
    user.save()
    messages.success(request, 'Usuário cadastrado com sucesso!')
    return redirect('login')


class UserUpdateView(UpdateView):
    model = User
    form_class = FormUpdateUser
    template_name = 'update_user.html'
    success_url = '/'
    #fields = ['matricula', 'chefia', 'setor', 'entrada',
    #          'saidaAlmoco', 'voltaAlmoco', 'saida']

accounts/templates/cadastro.html
{% extends 'base.html' %}

{% block content %}
<h1 calss="mt-3 mb-3">CADASTRO</h1>
<form method="POST" action="{% url 'cadastro' %}">
    {% include 'parciais/_messages.html' %}
    {% csrf_token %}
  <div class="form-group">
    <label>Nome</label>
    <input type="text" name="nome" value="{{ request.POST.nome }}" class="form-control" placeholder="Digite seu nome">
  </div>
    <div class="form-group">
    <label>Sobrenome</label>
    <input type="text" name="sobrenome" value="{{ request.POST.sobrenome }}" class="form-control" placeholder="Digite seu sobrenome">
  </div>
    <div class="form-group">
    <label>Matrícula</label>
    <input type="text" name="matricula" value="{{ request.POST.matricula }}" id="id_matricula" class="form-control mask-matricula" placeholder="###.###-#">
  </div>
     <div class="form-group">
    <label>Chefia imediata</label>
    <input type="text" name="chefia" value="{{ request.POST.chefia }}" class="form-control" placeholder="Digite o nome da chefia imediata">
  </div>
    <div class="form-group">
    <label>Setor</label>
    <input type="text" name="setor" value="{{ request.POST.setor }}" class="form-control" placeholder="Digite seu setor">
  </div>
    <div class="form-group">
    <label>Email</label>
    <input type="email" name="email" value="{{ request.POST.email }}" class="form-control" placeholder="abc@abc.com">
  </div>
    <div class="form-group">
    <label>Usuário</label>
    <input type="text" name="usuario" value="{{ request.POST.usuario }}" class="form-control" placeholder="Digite seu usuário">
  </div>
    <div class="form-group">
    <label>Entrada</label>
    <input type="text" name="entrada" value="{{ request.POST.entrada }}" class="form-control mask-entrada" placeholder="#:##">
  </div>
    <div class="form-group">
    <label>Saída do almoço</label>
    <input type="text" name="saidaAlmoco" value="{{ request.POST.saidaAlmoco }}" class="form-control mask-salmoco" placeholder="#:##">
  </div>
    <div class="form-group">
    <label>Volta do almoço</label>
    <input type="text" name="voltaAlmoco" value="{{ request.POST.voltaAlmoco }}" class="form-control mask-valmoco" placeholder="#:##">
  </div>
    <div class="form-group">
    <label>Saída</label>
    <input type="text" name="saida" value="{{ request.POST.saida }}" class="form-control mask-saida" placeholder="#:##">
  </div>
    <div class="form-group">
    <label>Senha</label>
    <input type="password" name="senha" class="form-control" placeholder="Digite sua senha">
  </div>
    <div class="form-group">
    <label>Repita a senha</label>
    <input type="password" name="senha2" class="form-control" placeholder="Repita sua senha">
  </div>

  <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>

{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h1 calss="mt-3 mb-3">LOGIN</h1>
<form method="POST" action="{% url 'login' %}">
    {% include 'parciais/_messages.html' %}
    {% csrf_token %}

    <div class="form-group">
    <label>Usuário</label>
    <input type="text" name="usuario" value="{{ request.POST.usuario }}" class="form-control" placeholder="Digite seu usuário">
  </div>
    <div class="form-group">
    <label>Senha</label>
    <input type="password" name="senha" class="form-control" placeholder="Digite sua senha">
  </div>

  <button type="submit" class="btn btn-primary">Cadastrar</button>
</form>

{% endblock %}

accounts/templates/logout.html
{% extends 'base.html' %}

{% block content %}
LOGOUT
{% endblock %}

accounts/templates/update_user.html
{% extends 'base.html' %}

{% block content %}
<h1 calss="mt-3 mb-3">ALTERAÇÃO</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Alterar">
    </form>

{% endblock %}